title: >
  <center><img src="http://www.nasa.gov/sites/all/themes/custom/nasatwo/images/nasa-logo.svg"></center>
  <a href="https://pytrain.github.io/web_prog/" style="color: white; text-decoration: none">Introduction to Web Programming</a>
  <h5><strong>Contact:</strong> brent dot smith at nasa dot gov,&nbsp;&nbsp;&nbsp; jules dot kouatchou at nasa dot gov</h5>
description: SSAI Hampton, July 29 & 30, 2019
theme: jekyll-theme-cayman
github:
  is_project_page: false
